'kinetics':
  data_path: ''
  jpg_video_path: ''
  video_path: ''
  annotation_path: ''

'ucf101':
  data_path: '/media/reza/2TB/Datasets/UCF101'
  jpg_video_path: 'jpg_video_directory'
  avi_video_path: 'videos'
  annotation_path: 'annotation_dir_path'

'hmdb51':
  data_path: ''
  jpg_video_path: ''
  video_path: ''
  annotation_path: ''