models:
  teacher:
    arch: res101
    pretrained_weights: '../weights'
    freeze_bbon: True

  student:
    arch: c3d

data:
  dataset: kinetics
  path: ''
  train_split: train_aug
  val_split: val
